const API_ENDPOINTS = {
  AUTH: {
    LOGIN: "/Auth/login",
    REGISTER: "/Auth/crear-usuario",
    RESET_PASSWORD: "/Auth/reiniciar-contrasenia",
    USERS: "/Auth/listar-usuarios",
  },
  USUARIO: {
    LIST: "/Usuario/listar",
    GET: "/Usuario/obtener",
    CREATE: "/Usuario/crear",
    UPDATE: "/Usuario/actualizar",
    DELETE: "/Usuario/eliminar",
    VALIDATE_CORREO: "/Usuario/validar-correo",
    CAMBIAR_PASSWORD: "/Usuario/cambiar-password",
    CAMBIAR_PASSWORD_PRIMER_LOGIN: "/Usuario/cambiar-password-primer-login",
    ACTIVAR_DESACTIVAR: "/Usuario/activar-desactivar",
  },
  ROL: {
    LIST: "/Rol/listar",
    GET: "/Rol/obtener",
    CREATE: "/Rol/crear",
    UPDATE: "/Rol/actualizar",
    DELETE: "/Rol/eliminar",
  },
  PERMISO: {
    LIST: "/Permiso/listar",
    GET: "/Permiso/obtener",
    ASIGNAR_ROL: "/Permiso/asignar-rol",
    REMOVER_ROL: "/Permiso/remover-rol",
    LISTAR_POR_ROL: "/Permiso/listar-por-rol",
  },
  CLIENTE: {
    LIST: "/Cliente/listar",
    GET: "/Cliente/obtener",
    SEARCH: "/Cliente/buscar",
    CREATE: "/Cliente/crear",
    UPDATE: "/Cliente/actualizar",
    DELETE: "/Cliente/eliminar",
    VALIDATE_CODE: "/Cliente/validar-codigo",
    VALIDATE_NIT: "/Cliente/validar-nit",
  },
  PRODUCTO: {
    LIST: "/Producto/listar",
    GET: "/Producto/obtener",
    SEARCH: "/Producto/buscar",
    CREATE: "/Producto/crear",
    UPDATE: "/Producto/actualizar",
    DELETE: "/Producto/eliminar",
    VALIDATE_CODE: "/Producto/validar-codigo",
  },
  PROVEEDOR: {
    LIST: "/Proveedor/listar",
    GET: "/Proveedor/obtener",
    SEARCH: "/Proveedor/buscar",
    CREATE: "/Proveedor/crear",
    UPDATE: "/Proveedor/actualizar",
    DELETE: "/Proveedor/eliminar",
    VALIDATE_NAME: "/Proveedor/validar-nombre",
  },
  MENU: {
    GET_MENU: "/Menu/Obtener-menu",
    GET_ALL_MENUS: "/Menu/Obtener-todos-menus",
  },
};

export default API_ENDPOINTS;